services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: e-school
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  e-school:
    image: ztp/e-school
    ports:
      - "3000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      MYSQL_HOST: "db"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
    depends_on:
      db:
        condition: service_healthy